# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in show_buckets.gemspec
gemspec

gem "rake", "~> 13.0"

gem "rspec", "~> 3.0"

gem "rubocop", "~> 1.21"

gem "aws-sdk-s3", "~> 1.182"

gem "rexml", "~> 3.4"
